name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_on_windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Install rebuild
      run: npm install electron-rebuild
    - name: Rebuild native modules
      run: npm run rebuild-win
    - name: Make app
      run: npm run make
